site_name: APPN Packaging
theme:
    name: 'material'
    palette:
      - scheme: 'default'
        media: '(prefers-color-scheme: light)'
        toggle:
          icon: 'material/lightbulb'
          name: "Switch to dark mode"
      - scheme: 'slate'
        media: '(prefers-color-scheme: dark)'
        primary: 'blue'
        toggle:
          icon: 'material/lightbulb-outline'
          name: 'Switch to light mode'

nav:
  - API Reference:
    - Schema: schema.md
    - Struct: struct.md
    - Graph: graph.md
    - Utility: utils.md

plugins:
  - search
  - autorefs
  - mkdocstrings:
      enable_inventory: true
      handlers:
        python:
          options:
            docstring_style: google
            show_source: false
            heading_level: 2
            members_order: source
            annotations_path: source
