__all__ = ("AnnotationError",)


class CoreException(BaseException): ...


class AnnotationError(CoreException): ...


class ValidationError(CoreException): ...


class IntegrityError(CoreException): ...
